name: Conflict label

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: needs rebase
          repoToken: ${{ secrets.GITHUB_TOKEN }}
